In [1]:
import numpy as np
import pandas as pd
x = np.array([1,2,3,4,5,6,6,7]) #as a list
print(type(x))
print(x.dtype)
print(x.size)
a = 12
print(type(a))

<class 'numpy.ndarray'>
int64
8
<class 'int'>

In [ ]:
y = np.array([1,2,3,4,5,6,7])#as a tupple
print(y)
print(type(y))
print(y.dtype)
print(y.size)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int64
7

In [ ]:
y = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
print(y)
print(type(y))
print(y.dtype)
print(y.size)

[1.1 2.2 3.3 4.4 5.5 6.6 7.7]
<class 'numpy.ndarray'>
float64
7

In [ ]:
y = np.array([[1.1,2.2,3.3,4.4,5.5,6.6,7.7],[1.1,2.2,3.3,4.4,5.5,6.6,7.7]])
print(y[0][0] + y[1][1])

3.3000000000000003

In [ ]:
z = ([1,2,3,4,5,56,6,7,8,8,9,98,67])

np.arange(1,22,3) #start:end:Condition

y = np.array([[1.1,2.2,3.3,4.4,5.5,6.6,7.7],[1.1,2.2,3.3,4.4,5.5,6.6,7.7]])
print(y.size)
a= y.shape
print(a)
print(y.reshape(2,7))

14
(2, 7)
[[1.1 2.2 3.3 4.4 5.5 6.6 7.7]
 [1.1 2.2 3.3 4.4 5.5 6.6 7.7]]

In [ ]:
#series
import pandas as pd
s = pd.Series([45,46,47,48,449])
print(s)
print(s.size)
print(s.shape)

s1 = pd.Series([45,46,47,48,449],index = range(100,105))
print(s1)
print(s1.size)
print(s1.shape)

0     45
1     46
2     47
3     48
4    449
dtype: int64
5
(5,)
100     45
101     46
102     47
103     48
104    449
dtype: int64
5
(5,)

In [ ]:
import pandas as pd

a=pd.Series([1,2,3,4,5])
b=pd.Series(['Vijay','Prakhar','Aryan','Sobaan','Swayam'])
c=pd.Series([12,14,16,18,20])
df = pd.DataFrame({
    'roll':a,
    'name':b,
    'marks':c
})
print(df)
print(df.shape)
print(df.dtypes)

   roll     name  marks
0     1    Vijay     12
1     2  Prakhar     14
2     3    Aryan     16
3     4   Sobaan     18
4     5   Swayam     20
(5, 3)
roll      int64
name     object
marks     int64
dtype: object

In [ ]:
import pandas as pd
import numpy as np
import os
os.getcwd()
df = pd.read_csv('student.csv')
print(df)
print(df.shape)
print(df.size)
print(df.columns)
print(df.dtypes)
print(df.T)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21
(10, 5)
50
Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')
roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object
           0      1       2        3      4       5      6      7      8  \
roll       1      2       3        4      5       6      7      8      9
name    anil   amit  aniket  ajinkya   asha  ayesha   amar  amita   amol
class     TE     TE      BE       TE     TE      BE     BE     BE     TE
marks  56.77  59.77   76.88    69.66  63.28   49.55  65.34  68.33  56.75
age       22     21      19       20     20      20     19     23     20

           9
roll      10
name   anmol
class     BE
marks  78.66
age       21
   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [ ]:
print(df.head())
print("\n")
print(df.head(3))
print("\n")
print(df.tail())
print("\n")
print(df.tail(2))

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20


   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19


   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21


   roll   name class  marks  age
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [ ]:
cols = ['A','B','C','D','E']
df1 = pd.read_csv('student1.csv',names= cols)
print(df1)

    A        B   C      D   E
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [ ]:
import pandas as pd
import numpy as np
import os

df3 = pd.read_csv('student3.tsv',sep = '\t')
df3

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [ ]:
df2 = pd.read_csv('student.csv',nrows=6)
df2

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20

In [ ]:
df.iloc[:8,1:4]

      name class  marks
0     anil    TE  56.77
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33

In [ ]:
df.iloc[1:8,1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33

df.iloc[5,2]

In [ ]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [ ]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [ ]:
df.name

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [ ]:
df.drop([5,8])

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21

In [ ]:
df.drop('class',axis = 1)

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [ ]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel' = None, *, axis: 'Axis' = 0, index: 'IndexLabel' = None, columns: 'IndexLabel' = None, level: 'Level' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the `user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        DataFrame without the removed index or column labels or
        None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    lama    speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [ ]:
df['marks'].mean()

64.499

In [ ]:
df['marks'].max()

78.66

In [ ]:
df['marks'].min()

49.55

In [ ]:
df['marks'].sum()

644.9899999999999

In [ ]:
df['marks'].median()

64.31

In [ ]:
df['marks'].std()

NameError: name 'df' is not defined

In [ ]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [ ]:
df.mean(numeric_only= True)

roll      5.500
marks    64.499
age      20.500
dtype: float64

In [ ]:
df.max()

roll         10
name     ayesha
class        TE
marks     78.66
age          23
dtype: object

In [ ]:
df.min()

roll           1
name     ajinkya
class         BE
marks      49.55
age           19
dtype: object

In [ ]:
df.count()

roll     10
name     10
class    10
marks    10
age      10
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 528.0+ bytes

In [ ]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [ ]:
df['marks'] = df['marks'] + 0.52
df

   roll     name class  marks  age
0     1     anil    TE  57.81   22
1     2     amit    TE  60.81   21
2     3   aniket    BE  77.92   19
3     4  ajinkya    TE  70.70   20
4     5     asha    TE  64.32   20
5     6   ayesha    BE  50.59   20
6     7     amar    BE  66.38   19
7     8    amita    BE  69.37   23
8     9     amol    TE  57.79   20
9    10    anmol    BE  79.70   21

In [ ]:
df['marks'] /10 + 0.27

0    6.051
1    6.351
2    8.062
3    7.340
4    6.702
5    5.329
6    6.908
7    7.207
8    6.049
9    8.240
Name: marks, dtype: float64

In [ ]:
df['cgpa'] = df['marks']/10 +0.27
df

   roll     name class  marks  age   cgpa
0     1     anil    TE  57.81   22  6.051
1     2     amit    TE  60.81   21  6.351
2     3   aniket    BE  77.92   19  8.062
3     4  ajinkya    TE  70.70   20  7.340
4     5     asha    TE  64.32   20  6.702
5     6   ayesha    BE  50.59   20  5.329
6     7     amar    BE  66.38   19  6.908
7     8    amita    BE  69.37   23  7.207
8     9     amol    TE  57.79   20  6.049
9    10    anmol    BE  79.70   21  8.240

In [ ]:
x = ['M','M','M','M','F','F','M','F','M','M']
df['gender'] = x
df

   roll     name class  marks  age   cgpa gender
0     1     anil    TE  57.81   22  6.051      M
1     2     amit    TE  60.81   21  6.351      M
2     3   aniket    BE  77.92   19  8.062      M
3     4  ajinkya    TE  70.70   20  7.340      M
4     5     asha    TE  64.32   20  6.702      F
5     6   ayesha    BE  50.59   20  5.329      F
6     7     amar    BE  66.38   19  6.908      M
7     8    amita    BE  69.37   23  7.207      F
8     9     amol    TE  57.79   20  6.049      M
9    10    anmol    BE  79.70   21  8.240      M

In [ ]:
df = pd.read_csv('student.csv')
ndf = pd.DataFrame({
    'roll': range(1,11),
    'cgpa':df['marks']/10 +0.27,
    'gender':['M','M','M','M','F','F','M','F','M','M']
})
ndf

   roll   cgpa gender
0     1  5.947      M
1     2  6.247      M
2     3  7.958      M
3     4  7.236      M
4     5  6.598      F
5     6  5.225      F
6     7  6.804      M
7     8  7.103      F
8     9  5.945      M
9    10  8.136      M

In [ ]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [ ]:
ndf.columns

Index(['roll', 'cgpa', 'gender'], dtype='object')

In [ ]:
df.merge(ndf,on='roll')

   roll     name class  marks  age   cgpa gender
0     1     anil    TE  56.77   22  5.947      M
1     2     amit    TE  59.77   21  6.247      M
2     3   aniket    BE  76.88   19  7.958      M
3     4  ajinkya    TE  69.66   20  7.236      M
4     5     asha    TE  63.28   20  6.598      F
5     6   ayesha    BE  49.55   20  5.225      F
6     7     amar    BE  65.34   19  6.804      M
7     8    amita    BE  68.33   23  7.103      F
8     9     amol    TE  56.75   20  5.945      M
9    10    anmol    BE  78.66   21  8.136      M

In [ ]:
df5 = pd.read_csv('student5.csv')
df5

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [ ]:
pd.concat([df,df5],ignore_index=True)

    roll     name class  marks  age
0      1     anil    TE  56.77   22
1      2     amit    TE  59.77   21
2      3   aniket    BE  76.88   19
3      4  ajinkya    TE  69.66   20
4      5     asha    TE  63.28   20
5      6   ayesha    BE  49.55   20
6      7     amar    BE  65.34   19
7      8    amita    BE  68.33   23
8      9     amol    TE  56.75   20
9     10    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20

In [ ]:
#STRING OPERATION

df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [ ]:
df['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [ ]:
df['name'].str.swapcase()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [ ]:
df['name'].str.startswith('an')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [ ]:
df['name'].str.endswith('l')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9     True
Name: name, dtype: bool

In [ ]:
df['name'].str.title()

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5     Ayesha
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [ ]:
df['name'].str.replace('l','ee')

0      aniee
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8      amoee
9     anmoee
Name: name, dtype: object

In [ ]:
x=df[df['marks']>60]#boolean filter true ko rakho and flase ko pheko
x

   roll     name class  marks  age
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21

In [ ]:
x.to_csv('output.csv',index= False)
x.to_html('output.csv',index = False)